# TWERKHUB - setup-hooks.ps1
# Installs git pre-commit hook that blocks commits with mojibake or BOM.
# Run once after cloning: powershell -ExecutionPolicy Bypass -File scripts\setup-hooks.ps1

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$hookDir = Join-Path $repoRoot '.git\hooks'
$hookPath = Join-Path $hookDir 'pre-commit'

if (-not (Test-Path $hookDir)) {
    Write-Host "ERROR: $hookDir does not exist. Are you inside a git repo?" -ForegroundColor Red
    exit 1
}

$hookContent = @'
#!/bin/sh
# TWERKHUB pre-commit hook - blocks mojibake and BOM
# Generated by scripts/setup-hooks.ps1
# Uses xargs to chunk file list (avoids "Argument list too long" on large commits)

# Get staged source files
git diff --cached --name-only --diff-filter=AM \
  | grep -E '\.(html|css|js|mjs|json|xml|svg|md|txt|yml|yaml)$' \
  > .git/.pre-commit-staged.txt

if [ ! -s .git/.pre-commit-staged.txt ]; then
  rm -f .git/.pre-commit-staged.txt
  exit 0
fi

# Run check-encoding in batches of 100 files (xargs handles arg-list limits)
status=0
xargs -a .git/.pre-commit-staged.txt -d '\n' -n 100 node scripts/check-encoding.js
if [ $? -ne 0 ]; then status=1; fi

rm -f .git/.pre-commit-staged.txt

if [ $status -ne 0 ]; then
  echo ""
  echo "[BLOCKED] Pre-commit hook detected encoding issues."
  echo "  Fix the issues above, then re-run: git add files && git commit"
  echo "  Bypass (only if necessary): git commit --no-verify"
  exit 1
fi

exit 0
'@

[System.IO.File]::WriteAllText($hookPath, $hookContent.Replace("`r`n", "`n"), (New-Object System.Text.UTF8Encoding $false))

Write-Host "[OK] Pre-commit hook installed at: $hookPath" -ForegroundColor Green
Write-Host ""
Write-Host "Test it: make a tiny change to any HTML, then 'git add' + 'git commit -m test'."
Write-Host "If file is clean, commit goes through. If mojibake/BOM detected, commit is blocked."
Write-Host ""
Write-Host "To bypass in an emergency: git commit --no-verify"
